import type { IndicatorDef } from "./types";

export const INDICATORS: IndicatorDef[] = [
  {
    id: "YC",
    name: "Yield Curve",
    technicalName: "10-Year minus 2-Year Treasury Spread",
    weight: 9,
    safeThreshold: 0.5,
    criticalThreshold: -0.3,
    description:
      "The gap between long and short-term government bond rates. When it flips negative, a recession has historically followed.",
    source: "FRED T10Y2Y",
    frequency: "Daily",
    inverted: true,
  },
  {
    id: "IC",
    name: "Weekly Layoff Filings",
    technicalName: "Initial Jobless Claims, 4-Week Moving Average",
    weight: 8,
    safeThreshold: 220000,
    criticalThreshold: 350000,
    description:
      "How many Americans filed for unemployment benefits this week. Rising numbers mean companies are cutting jobs.",
    source: "FRED IC4WSA",
    frequency: "Weekly",
    inverted: false,
  },
  {
    id: "SR",
    name: "Unemployment Pace",
    technicalName: "Sahm Rule Recession Indicator",
    weight: 9,
    safeThreshold: 0.0,
    criticalThreshold: 0.5,
    description:
      "How quickly unemployment is rising. This measure has triggered at the start of every recession since 1970.",
    source: "FRED SAHMREALTIME",
    frequency: "Monthly",
    inverted: false,
  },
  {
    id: "HY",
    name: "Corporate Borrowing Stress",
    technicalName: "ICE BofA US High Yield Index Option-Adjusted Spread",
    weight: 7,
    safeThreshold: 3.5,
    criticalThreshold: 7.0,
    description:
      "How much extra interest risky companies pay to borrow money. Rising costs mean investors fear more defaults.",
    source: "FRED BAMLH0A0HYM2",
    frequency: "Daily",
    inverted: false,
  },
  {
    id: "BR",
    name: "Market Breadth",
    technicalName: "S&P 500 Percentage of Stocks Above 200-Day Moving Average",
    weight: 6,
    safeThreshold: 60,
    criticalThreshold: 25,
    description:
      "What percentage of major stocks are in a healthy trend. When only a few stocks carry the market, it\u2019s fragile.",
    source: "Yahoo Finance",
    frequency: "Daily",
    inverted: true,
  },
  {
    id: "HP",
    name: "Home Construction",
    technicalName: "Building Permits, Year-over-Year % Change",
    weight: 6,
    safeThreshold: 5,
    criticalThreshold: -25,
    description:
      "How many new building permits are being filed compared to last year. Housing leads the economy by over a year.",
    source: "FRED PERMIT",
    frequency: "Monthly",
    inverted: true,
  },
  {
    id: "SV",
    name: "Services Economy",
    technicalName: "ISM Services PMI",
    weight: 6,
    safeThreshold: 53,
    criticalThreshold: 46,
    description:
      "Is the services sector \u2014 77% of the economy \u2014 growing or shrinking? Below 50 means contraction.",
    source: "ISM / FRED proxy",
    frequency: "Monthly",
    inverted: true,
  },
  {
    id: "IN",
    name: "Insider Selling",
    technicalName: "Corporate Insider Sell/Buy Ratio",
    weight: 5,
    safeThreshold: 3.0,
    criticalThreshold: 10.0,
    description:
      "Are corporate executives buying or selling their own company\u2019s stock? Heavy selling means insiders are nervous.",
    source: "SEC EDGAR / OpenInsider",
    frequency: "Weekly",
    inverted: false,
  },
  {
    id: "JP",
    name: "Hiring Slowdown",
    technicalName: "Job Posting Velocity, Year-over-Year % Change",
    weight: 6,
    safeThreshold: 0,
    criticalThreshold: -20,
    description:
      "How fast companies are pulling job postings. Captures quiet hiring freezes before layoffs are announced.",
    source: "Indeed Hiring Lab",
    frequency: "Weekly",
    inverted: true,
  },
  {
    id: "GT",
    name: "Public Worry",
    technicalName: "Google Trends Recession Anxiety Index (normalized)",
    weight: 4,
    safeThreshold: 1.0,
    criticalThreshold: 2.5,
    description:
      'How often people are searching for "recession," "layoffs," and "unemployment" on Google.',
    source: "Google Trends API",
    frequency: "Weekly",
    inverted: false,
  },
  {
    id: "TE",
    name: "Temp Worker Cuts",
    technicalName: "Temporary Help Services Employment, Year-over-Year % Change",
    weight: 5,
    safeThreshold: 2.0,
    criticalThreshold: -5.0,
    description:
      "Companies let go of temporary workers before permanent staff \u2014 an early warning sign of broader layoffs.",
    source: "FRED TEMPHELPS",
    frequency: "Monthly",
    inverted: true,
  },
  {
    id: "CF",
    name: "Crypto Stress",
    technicalName: "Crypto Fear & Greed Index + BTC-SPX Correlation",
    weight: 4,
    safeThreshold: 40,
    criticalThreshold: 15,
    description:
      "When crypto markets show extreme fear while moving in lockstep with stocks, all risky investments are being sold.",
    source: "Alternative.me / CoinGecko",
    frequency: "Daily",
    inverted: true,
  },
];
